name: Build and deploy

on:
  push:
    branches:
      - main
env:
  PROJECT_ID:  ${{ secrets.GKA_PROJECT }}
  GKE_CLUSTER: cluster-1-tharindu
  GKE_ZONE: us-central1-c
  DEPLOYMENT_NAME: tharindu-springhello-deployment
  IMAGE: tharindu-springhello-image
  TAGE: 1.0.0

jobs:
  setup-build-publish-deploy:
    name: Setup Build Publish Deploy
    runs-on: ubuntu-latest

    steps:
      - run : echo "Build started "
      - name: Checkout repository
        uses: actions/checkout@v3
      - run : echo "Project repository has been clone in to the runner"

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: github
          settings-path: ${{ github.workspace}}
    
      - name: Build with maven
        run : mvn clean package -DskipTests





  







