name: Build and deploy

on:
  push:
    branches:
      - main
env:
  PROJECT_ID:  ${{ secrets.GKA_PROJECT }}
  GKE_CLUSTER: cluster-1-tharindu
  GKE_ZONE: us-central1-c
  DEPLOYMENT_NAME: tharindu-springhello-deployment
  IMAGE: tharindu-springhello-image
  TAGE: 1.0.0

jobs:
  setup-build-publish-deploy:
    name: Setup Build Publish Deploy
    runs-on: ubuntu-latest

    steps:
      - run : echo "Build started "
      - name: Checkout repository
        uses: actions/checkout@v3
      - run : echo "Project repository has been clone in to the runner"

      - name: Setup JDK 11
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
    
      - name: Build with maven
        run : mvn clean package -DskipTests





  







