name: Build and deploy

on:
  push:
    branches:
      - main
env:
  PROJECT_ID: ${{ secrets.GKA_PROJECT }}
  GKE_CLUSTER: cluster-1-tharindu
  GKE_ZONE: us-central1-c
  DEPLOYMENT_NAME: tharindu-springhello-deployment
  IMAGE: tharindu-springhello-image
  TAG: 1.0.0

jobs:
  setup-build-publish:
    name: Setup Build Publish Deploy
    runs-on: ubuntu-latest

    steps:
      - run: echo "Build started "
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: echo "Project repository has been clone in to the runner"

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          server-id: github
          settings-path: ${{ github.workspace}}

      - name: Build with maven
        run: mvn clean package -DskipTests
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/springhello:latest

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.gcp_credentials }}"

      # Setup gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      # Get the GKE credentials so we can deploy to the cluster
      - run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
